# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: consensus.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63onsensus.proto\x12\tconsensus\"/\n\x0bVoteRequest\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x11\n\tsender_id\x18\x02 \x01(\x05\"+\n\x0cVoteResponse\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x0c\n\x04vote\x18\x02 \x01(\t\"K\n\x15GlobalDecisionRequest\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x10\n\x08\x64\x65\x63ision\x18\x02 \x01(\t\x12\x11\n\tsender_id\x18\x03 \x01(\x05\"$\n\x03\x41\x63k\x12\r\n\x05tx_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t2\xd1\x01\n\x10\x43onsensusService\x12\x37\n\x04Vote\x12\x16.consensus.VoteRequest\x1a\x17.consensus.VoteResponse\x12\x42\n\x0eGlobalDecision\x12 .consensus.GlobalDecisionRequest\x1a\x0e.consensus.Ack\x12@\n\x0cSelfDecision\x12 .consensus.GlobalDecisionRequest\x1a\x0e.consensus.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'consensus_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTEREQUEST']._serialized_start=30
  _globals['_VOTEREQUEST']._serialized_end=77
  _globals['_VOTERESPONSE']._serialized_start=79
  _globals['_VOTERESPONSE']._serialized_end=122
  _globals['_GLOBALDECISIONREQUEST']._serialized_start=124
  _globals['_GLOBALDECISIONREQUEST']._serialized_end=199
  _globals['_ACK']._serialized_start=201
  _globals['_ACK']._serialized_end=237
  _globals['_CONSENSUSSERVICE']._serialized_start=240
  _globals['_CONSENSUSSERVICE']._serialized_end=449
# @@protoc_insertion_point(module_scope)
