# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import consensus_pb2 as consensus__pb2


class ConsensusServiceStub(object):
    """============ SERVICE ============
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Vote = channel.unary_unary(
                '/consensus.ConsensusService/Vote',
                request_serializer=consensus__pb2.VoteRequest.SerializeToString,
                response_deserializer=consensus__pb2.VoteResponse.FromString,
                )
        self.GlobalDecision = channel.unary_unary(
                '/consensus.ConsensusService/GlobalDecision',
                request_serializer=consensus__pb2.GlobalDecisionRequest.SerializeToString,
                response_deserializer=consensus__pb2.Ack.FromString,
                )
        self.SelfDecision = channel.unary_unary(
                '/consensus.ConsensusService/SelfDecision',
                request_serializer=consensus__pb2.GlobalDecisionRequest.SerializeToString,
                response_deserializer=consensus__pb2.Ack.FromString,
                )


class ConsensusServiceServicer(object):
    """============ SERVICE ============
    """

    def Vote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GlobalDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SelfDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConsensusServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Vote': grpc.unary_unary_rpc_method_handler(
                    servicer.Vote,
                    request_deserializer=consensus__pb2.VoteRequest.FromString,
                    response_serializer=consensus__pb2.VoteResponse.SerializeToString,
            ),
            'GlobalDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.GlobalDecision,
                    request_deserializer=consensus__pb2.GlobalDecisionRequest.FromString,
                    response_serializer=consensus__pb2.Ack.SerializeToString,
            ),
            'SelfDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SelfDecision,
                    request_deserializer=consensus__pb2.GlobalDecisionRequest.FromString,
                    response_serializer=consensus__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'consensus.ConsensusService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ConsensusService(object):
    """============ SERVICE ============
    """

    @staticmethod
    def Vote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/consensus.ConsensusService/Vote',
            consensus__pb2.VoteRequest.SerializeToString,
            consensus__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GlobalDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/consensus.ConsensusService/GlobalDecision',
            consensus__pb2.GlobalDecisionRequest.SerializeToString,
            consensus__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SelfDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/consensus.ConsensusService/SelfDecision',
            consensus__pb2.GlobalDecisionRequest.SerializeToString,
            consensus__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
