# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"8\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\"6\n\x10RequestVoteReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\":\n\x08LogEntry\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\"n\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\x12\x1f\n\x07\x65ntries\x18\x03 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x14\n\x0c\x63ommit_index\x18\x04 \x01(\x05\"H\n\x12\x41ppendEntriesReply\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0b\x66ollower_id\x18\x03 \x01(\x05\"<\n\x14\x43lientRequestMessage\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x11\n\toperation\x18\x02 \x01(\t\"I\n\x12\x43lientReplyMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tleader_id\x18\x03 \x01(\x05\x32\xd9\x01\n\x08RaftNode\x12?\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x16.raft.RequestVoteReply\x12\x45\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x18.raft.AppendEntriesReply\x12\x45\n\rClientRequest\x12\x1a.raft.ClientRequestMessage\x1a\x18.raft.ClientReplyMessageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTVOTEREQUEST']._serialized_start=20
  _globals['_REQUESTVOTEREQUEST']._serialized_end=76
  _globals['_REQUESTVOTEREPLY']._serialized_start=78
  _globals['_REQUESTVOTEREPLY']._serialized_end=132
  _globals['_LOGENTRY']._serialized_start=134
  _globals['_LOGENTRY']._serialized_end=192
  _globals['_APPENDENTRIESREQUEST']._serialized_start=194
  _globals['_APPENDENTRIESREQUEST']._serialized_end=304
  _globals['_APPENDENTRIESREPLY']._serialized_start=306
  _globals['_APPENDENTRIESREPLY']._serialized_end=378
  _globals['_CLIENTREQUESTMESSAGE']._serialized_start=380
  _globals['_CLIENTREQUESTMESSAGE']._serialized_end=440
  _globals['_CLIENTREPLYMESSAGE']._serialized_start=442
  _globals['_CLIENTREPLYMESSAGE']._serialized_end=515
  _globals['_RAFTNODE']._serialized_start=518
  _globals['_RAFTNODE']._serialized_end=735
# @@protoc_insertion_point(module_scope)
