# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: two_pc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'two_pc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctwo_pc.proto\x12\x05twopc\" \n\x0f\x44\x65\x63isionRequest\x12\r\n\x05tx_id\x18\x01 \x01(\t\"\x1f\n\rDecisionReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\x8c\x01\n\x0f\x44\x65\x63isionService\x12<\n\x0cGlobalCommit\x12\x16.twopc.DecisionRequest\x1a\x14.twopc.DecisionReply\x12;\n\x0bGlobalAbort\x12\x16.twopc.DecisionRequest\x1a\x14.twopc.DecisionReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_pc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECISIONREQUEST']._serialized_start=23
  _globals['_DECISIONREQUEST']._serialized_end=55
  _globals['_DECISIONREPLY']._serialized_start=57
  _globals['_DECISIONREPLY']._serialized_end=88
  _globals['_DECISIONSERVICE']._serialized_start=91
  _globals['_DECISIONSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
